[package]
name = "dau"
version = "0.1.0"
authors = ["Steve Smith <tarkasteve@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.25"
libc = "0.2.66"
log = "0.4.8"
simplelog = "0.7.4"
structopt = "0.3.5"
thiserror = "1.0.9"
toml = "0.5.5"

[dev-dependencies]
escargot = "0.5.0"
